baseURL = 'https://bojunjin.com/'
languageCode = 'en-us'
title = 'David Bojun Jin'
copyright = "© David Jin"
theme = "minima"
paginate = 7

# Author has some of your information to be shown on the home 
# page of your blog.
[author]
name = "Hi, I'm David🇨🇳🇳🇿"
slogon = "An experienced software engineer interested in distributed systems, computer graphics, functional programming, and iOS development."

[params]
# iam is the beginning words of your self-introduction.
# iam = "I am"
# # The subtitle will be shown after the title of your blog site
# #  in a format "title - subtitle".
# subtitle = "ddd"

# Params.social is an array containing your social network accounts,
# Each has a lowercase name, a svg formatted icon and a url to the 
# webpage of your account. They will be shown at the bottom of every
# page of your blog. 
# Be sure the svgs you select to use must have both the width and the
# height set 18. If you don't wanna put the svg code in this config
# file, you can instead save them to the `data/svg.toml` file under 
# the root directory of your blog using a format like `name = '<svg>'`
[[params.social]]
name = "github"
url = "https://github.com/davidjin0418"
svg = ""
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/david-bojun-jin/"
svg = ""


# Menu.main is an array that's used to decide what entries can be shown
# on the navigator of yur blog. You can use a weight to make them ordered.
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Categories"
url = "/categories"
weight = 2
[[menu.main]]
name = "Series"
url = "/series"
weight = 3
# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 4


# You can classify your posts by setting taxanomies in the front matter like
# categories = ["apple", "banana"]
# series = ["s1", "s2"]
# tags = ["t1", "t2"]
# A little suggestion: one post belongs to one series, one category and multiple tags.
[taxonomies]
category = "categories"
tag = "tags"
series = "series"


# Make sure all the codes in a post are highlighted correctly
# so better not edit this.
[markup.highlight]
lineNos = true
noClasses = false

[deployment]

[[deployment.targets]]
name = "bojunjin.com"
URL = "s3://bojunjin.com?region=ap-southeast-2"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
# cloudFrontDistributionID =	"[CLOUDFRONT_DIST_ID]"

# [[deployment.matchers]]
# Cache static assets for 20 years.
# pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
# cacheControl = "max-age=630720000, no-transform, public"
# gzip = true

# [[deployment.matchers]]
# pattern = "^.+\\.(html|xml|json)$"
# gzip = true